name: Gearboy CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  macos:
    name: macOS-arm64
    runs-on: [self-hosted, macos, ARM64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: brew install sdl2
    - name: make
      run: make dist
      working-directory: platforms/macos
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: macOS App bundle
        path: platforms/macos/Gearboy.app
